[package]
name = "pistonproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
serde_json = "1.0.140"
